//import java.util.*;
//
//public class Exception03 {
//	public static void main(String[] args) {
//		int [] arr = {10,20,30};
//		try {
//			for(int i = 0;i<=3;i++) {
//				System.out.println("arr[" + i + "] : " + arr[i]);
//			}
//		}
//		catch(Exception e) {
//			System.out.println("예외처리입니다....");
//			System.out.println(e.getMessage());
//		}
//		finally {
//			System.out.println("예외 발생 여부와 상관없이 실행됩니다.");
//		}
//	}
//}
