import java.lang.Exception;
import java.util.*;
//
//class MyException extends Exception{
//	String str1;
//	MyException(String str2){
//		str1 = str2;
//	}
//	public String toString() {
//		return ("MyException 발생 " + str1);
//	}
//}
//
//public class Exception06 {
//	public static void main(String[] args) {
//		try {
//			System.out.println("try 블록입니다.");
//			throw new MyException("MyException 클래스 호출");
//		} catch(MyException e){
//			System.out.println("catch 블록입니다.");
//			System.out.println(e);
//		}
//	}
//}



//class MyException extends Exception{
////	String str1;
////	MyException(String str2){
////		this.str1 = str2;
////	}
////	public String toString() {
////		return ("MyException발생: " + str1);
////	}
//	public MyException(String s) {
//		super(s);
//	}
//}
//
//public class Exception06{
//	public static void main(String [] args) {
//		try {
//			System.out.println("try 블록입니다.");
//			throw new MyException("MyException클래스 호출됩니다.");
//		}
//		catch(MyException e) {
//			System.out.println("catch블록입니다.");
//			System.out.println(e);
//		}
//	}
//}
